# Generated by Django 6.0.2 on 2026-02-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('service_type', models.CharField(choices=[('ambulant', 'Ambulant'), ('interne', 'Interne')], max_length=20)),
            ],
        ),
    ]
