# Generated by Django 6.0.2 on 2026-02-26 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_visit_consultation_done_visit_laboratory_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField(default=1)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('private', 'Privée'), ('semi_private', 'Semi-Privée'), ('intensive', 'Soins Intensifs')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('free', 'Libre'), ('occupied', 'Occupée'), ('cleaning', 'Nettoyage'), ('maintenance', 'Maintenance')], default='free', max_length=20)),
                ('capacity', models.IntegerField(default=1)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('features', models.TextField(blank=True, help_text='Equipment and features in the room')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('free', 'Libre'), ('occupied', 'Occupée'), ('cleaning', 'Nettoyage'), ('reserved', 'Réservée')], default='free', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='patients.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='RoomTab.room')),
            ],
            options={
                'ordering': ['room', 'bed_number'],
                'unique_together': {('room', 'bed_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('admission', 'Admission'), ('transfer', 'Transfert'), ('discharge', 'Sortie')], default='admission', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='RoomTab.bed')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='patients.patient')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
