# Generated by Django 6.0.2 on 2026-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patient_type_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='consultation_done',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='laboratory_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='pharmacy_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='prescription_done',
            field=models.BooleanField(default=False),
        ),
    ]
