# Generated by Django 6.0.2 on 2026-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Indique si l'utilisateur est actuellement en ligne",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, help_text="Dernière activité de l'utilisateur", null=True
            ),
        ),
    ]
